Repository codebuddies/codebuddies, pull requests merged in 2018-02, with the labels that each got.

#778 Welcome page template, copy, route
  client/templates/other/welcome.html
  lib/routes.js
Labels: Waiting For Review, ready

#786 Issue 742 - updated email templates
  private/email-hangout-alerts.html
  private/email-hangout-followup.html
  private/email-hangout-reminder-two.html
  private/email-hangout-reminder.html
Labels: Waiting For Review

#782 Issue 750 new hangout slack channel announcements
  client/templates/study_groups/study_group_settings.html
  client/templates/study_groups/study_group_settings.js
  i18n/en.i18n.json
  server/hangouts/methods.js
  server/slack/methods.js
  server/study_groups/methods.js
Labels: In Review

#788 Temporary removal of links
  client/css/_home.scss
  client/templates/nav/header.html
  client/templates/study_groups/single_study_group.html
Labels: Waiting For Review

#792 Add forgotten slack channels
  imports/data/slack_channels.js
Labels: Waiting For Review

#793 Add forgotten slack channels to prod
  imports/data/slack_channels.js
Labels: Waiting For Review

#795 Removing force-ssl, adding Dockerfile
  .meteor/packages
  .meteor/versions
  Dockerfile
Labels: Waiting For Review

#797 Edit typo at Line 35
  readme.md
Labels: Waiting For Review

#796 Issue 581 add Join/Leave study group in study group pages
  client/css/_study_groups.scss
  client/templates/study_groups/all_study_groups.html
  client/templates/study_groups/all_study_groups.js
  client/templates/study_groups/my_study_groups.html
  client/templates/study_groups/my_study_groups.js
  client/templates/study_groups/study_group_search_result.html
  client/templates/study_groups/study_group_search_result.js
Labels: In Review

#798 Fix Issue #790: _select2.css changes
  client/compatibilities/select2/_select2.css
Labels: Waiting For Review
