Repository codebuddies/codebuddies, pull requests merged in 2018-04, with the labels that each got.

#803 Issue 800 alert hangout cb channel
  server/hangouts/methods.js
Labels: In Review

#805 Encode google calendar topic/description
  client/templates/hangout/hangout.html
  client/templates/hangout/hangout.js
  client/templates/hangout/hangout_action_buttons.js
  i18n/en.i18n.json
  i18n/es.i18n.json
Labels: In Review

#801 Email notifications
  client/css/_base.scss
  client/templates/discussion/add_discussion_modal.html
  client/templates/discussion/all_discussions.html
  client/templates/discussion/all_discussions.js
  client/templates/discussion/discussion_card.html
  client/templates/discussion/discussion_item.html
  client/templates/discussion/discussion_responses_list.html
  client/templates/nav/header.html
  client/templates/study_groups/single_study_group.html
  imports/libs/server/cb_mailer/index.js
  imports/libs/server/cron/helpers.js
  imports/libs/server/cron/initial_email_notifications.js
  package.json
  private/templates/email/new_discussion.html
  private/templates/email/new_discussion_response.html
  private/templates/email/new_hangout.html
  private/templates/email/new_member.html
  server/cron_job/methods.js
  server/discussion_responses/methods.js
  server/discussions/methods.js
  server/hangouts/methods.js
  server/slack/methods.js
  server/study_groups/methods.js
Labels: Waiting For Review

#810 Resolves issue 809: solve formatting issues and link up usernames
  client/css/_discussion.scss
  client/templates/discussion/discussion_card.html
  client/templates/discussion/discussion_item.html
  client/templates/discussion/discussion_item.js
  client/templates/discussion/discussion_response_card.html
  client/templates/discussion/discussion_response_card.js
  client/templates/discussion/discussion_sidebar_participant_list.html
Labels: in progress

#808 Updated contributors' section on the About page (and added a proper "contributors" section to the Github README.md)
  .all-contributorsrc
  client/templates/other/about.html
  imports/data/contributors.json
  imports/libs/server/cron/initial_email_notifications.js
  package-lock.json
  package.json
  readme.md
Labels: in progress

#812 Small `contributors` fix
  imports/data/contributors.json
Labels: in progress

#813 Edit discussion tags
  client/templates/discussion/all_discussions.html
  imports/data/discussion_tags.js
Labels: in progress

#814 Change slack signin permissions
  client/layouts/layout.js
  client/templates/hangout/hangout-item.js
  client/templates/hangout/hangout.js
  client/templates/hangout/hangout_card.js
  client/templates/home/home_logged_in.js
  client/templates/home/home_logged_out.js
  client/templates/main.js
  client/templates/nav/header.js
  client/templates/status/status-list.js
  client/templates/status/update-status.js
  server/mailchimp.js
  server/main.js
Labels: in progress

#815 Refactor settings
  .gitignore
  server/main.js
  settings-development.json
Labels: in progress

#820 Fixed #818
  client/css/_hangout_card.scss
Labels: Waiting For Review

#827 Fixed #825
  client/templates/main.js
Labels: Waiting For Review

#836 use another dockerfile
  Dockerfile
Labels: in progress

#839 solving issue: #837 overflow problem of bigger links in discussion thread
  client/css/_discussion.scss
Labels: Waiting For Review

#842 Migration 1.6
  .meteor/.finished-upgraders
  .meteor/packages
  .meteor/release
  .meteor/versions
  package-lock.json
  package.json
Labels: in progress

#843 Mini release
  .meteor/.finished-upgraders
  .meteor/packages
  .meteor/release
  .meteor/versions
  Dockerfile
  client/css/_discussion.scss
  client/css/_hangout_card.scss
  client/templates/hangout/hangout-item.js
  client/templates/hangout/hangout-list.html
  client/templates/hangout/hangout-list.js
  client/templates/hangout/hangout.js
  client/templates/hangout/hangout_action_buttons.html
  client/templates/hangout/hangout_action_buttons.js
  client/templates/hangout/hangout_card.js
  client/templates/home/home_logged_in.html
  client/templates/home/home_logged_in.js
  client/templates/home/home_logged_out.html
  client/templates/home/home_logged_out.js
  client/templates/main.js
  client/templates/status/update-status.js
  package-lock.json
  package.json
Labels: in progress

#845 Ci improvements
  .meteor/packages
  .meteor/versions
  client/head.html
  package-lock.json
  package.json
Labels: in progress

#841 add commit hook using prettier, husky and lint-staged
  package-lock.json
  package.json
  readme.md
  server/main.js
  server/sitemaps.js
Labels: in progress

#846 Update Dockerfile for meteor 1.6
  Dockerfile
Labels: in progress

#838 Issue 784 opt out learning tweet
  client/templates/hangout/hangout-learned.html
  client/templates/hangout/hangout-learned.js
  server/learnings/methods.js
  server/twitter/methods.js
Labels: In Review, in progress

#853 add prettierignore
  .meteor/packages
  .prettierignore
  Dockerfile
  package-lock.json
  package.json
Labels: in progress

#857 Bug fix: Hide google calendar button in completed hangout
  client/templates/hangout/hangout.html
  client/templates/hangout/hangout.js
  client/templates/hangout/hangout_action_buttons.html
  client/templates/hangout/hangout_action_buttons.js
Labels: in progress

#855 fix (Slack notifications): Remove mention of "username" in Slack notif…
  server/slack/methods.js
Labels: in progress

#858 Bug fix: Owner of completed hangout can create hangout
  client/templates/hangout/hangout_action_buttons.html
Labels: in progress

#860 Staging fix (Release 1.1)
  .meteor/packages
  .meteor/versions
  .prettierignore
  Dockerfile
  client/head.html
  client/templates/hangout/hangout-learned.html
  client/templates/hangout/hangout-learned.js
  client/templates/hangout/hangout.html
  client/templates/hangout/hangout.js
  client/templates/hangout/hangout_action_buttons.html
  client/templates/hangout/hangout_action_buttons.js
  package-lock.json
  package.json
  readme.md
  server/learnings/methods.js
  server/main.js
  server/sitemaps.js
  server/slack/methods.js
  server/twitter/methods.js
Labels: in progress
