Repository codebuddies/codebuddies, pull requests merged in 2018-07, with the labels that each got.

#915 Issue 868 archive data
  .gitignore
  server/archived_users/methods.js
  server/discussion_responses/methods.js
  server/discussions/methods.js
  server/github_api_calls.js
  server/study_groups/methods.js
Labels: in progress

#918 Fix: Unable to start app on osx
  .meteor/packages
  .meteor/versions
  client/css/_sponsor.scss
Labels: Waiting For Review

#920 Release 1.2
  .gitignore
  .meteor/packages
  .meteor/versions
  client/css/_home.scss
  client/css/_sponsor.scss
  client/head.html
  client/templates/hangout/hangout-frame.js
  client/templates/hangout/hangout.html
  client/templates/hangout/support_hangout_organizer.html
  client/templates/hangout/support_hangout_organizer.js
  client/templates/home/home_logged_out.html
  client/templates/other/coworking.html
  client/templates/other/coworking.js
  client/templates/profile/profile-edit/profile-edit.html
  client/templates/profile/profile-edit/profile-edit.js
  client/templates/profile/profile.html
  server/app_stats/methods.js
  server/archived_users/methods.js
  server/browser_policy.js
  server/discussion_responses/methods.js
  server/discussions/methods.js
  server/github_api_calls.js
  server/study_groups/methods.js
  server/users/methods.js
Labels: Waiting For Review

#925 FontAwesome cleanup: use fas instead of far (pro) icons
  client/css/_hangout_list.scss
  client/templates/admin/report/report_discussion_modal.html
  client/templates/admin/report/report_hangout_modal.html
  client/templates/discussion/discussion_card.html
  client/templates/discussion/discussion_item.html
  client/templates/discussion/discussion_response_card.html
  client/templates/hangout/hangout-clone.html
  client/templates/hangout/hangout-edit.html
  client/templates/hangout/hangout-item.html
  client/templates/hangout/hangout-modal.html
  client/templates/hangout/hangout.html
  client/templates/hangout/hangout_action_buttons.html
  client/templates/hangout/hangout_card.html
  client/templates/hangout/support_hangout_organizer.html
  client/templates/other/page-not-found.html
  client/templates/profile/profile.html
  client/templates/status/learning-item.html
  client/templates/status/status-item.html
  client/templates/study_groups/study_group_discussion.html
Labels: Waiting For Review

#923 Meteor 1.7 Upgrade
  .meteor/.finished-upgraders
  .meteor/packages
  .meteor/release
  .meteor/versions
  package-lock.json
  package.json
Labels: Waiting For Review, could use code review

#929 Updated /slack etiquette section, _slack.scss, and head.html
  client/css/_slack.scss
  client/head.html
  client/templates/other/slack.html
Labels: Waiting For Review

#928 add forum link in nav bar
  client/templates/nav/header.html
Labels: Waiting For Review
