Repository codebuddies/codebuddies, pull requests merged in 2018-05, with the labels that each got.

#866 Fix Mixed Content Error
  client/head.html
Labels: Waiting For Review

#856 #830 Add global activity feed on home logged out page
  client/css/_home.scss
  client/templates/home/home_logged_out.html
  client/templates/home/home_logged_out.js
  client/templates/main.js
  i18n/en.i18n.json
  server/hangouts/publications.js
  server/home/methods.js
Labels: in progress

#870 Enable PR's to be built on Dockercloud
  Dockerfile
  docker-compose.test.yml
Labels: Waiting For Review, in progress

#864 Join study group prompt login
  client/templates/study_groups/all_study_groups.html
  client/templates/study_groups/all_study_groups.js
Labels: in progress

#869 Fixed issue #861
  client/templates/home/home_logged_out.html
Labels: Waiting For Review

#872 Enable docker containers for PR's
  docker-compose.test.yml
  hooks/post_test
Labels: Waiting For Review

#873 Adding contributor
  imports/data/contributors.json
  readme.md
Labels: Waiting For Review

#874 Feat montiapm
  .meteor/packages
  .meteor/versions
  server/monti.js
  settings-development.json
Labels: Waiting For Review

#875 Release 1.11
  .meteor/packages
  .meteor/versions
  client/css/_home.scss
  client/head.html
  client/templates/home/home_logged_out.html
  client/templates/home/home_logged_out.js
  client/templates/main.js
  client/templates/study_groups/all_study_groups.html
  client/templates/study_groups/all_study_groups.js
  docker-compose.test.yml
  hooks/post_test
  i18n/en.i18n.json
  imports/data/contributors.json
  package-lock.json
  readme.md
  server/hangouts/publications.js
  server/home/methods.js
  server/monti.js
  settings-development.json
Labels: Waiting For Review

#878 Revert "Release 1.11"
  .meteor/packages
  .meteor/versions
  client/css/_home.scss
  client/head.html
  client/templates/home/home_logged_out.html
  client/templates/home/home_logged_out.js
  client/templates/main.js
  client/templates/study_groups/all_study_groups.html
  client/templates/study_groups/all_study_groups.js
  docker-compose.test.yml
  hooks/post_test
  i18n/en.i18n.json
  imports/data/contributors.json
  package-lock.json
  readme.md
  server/hangouts/publications.js
  server/home/methods.js
  server/monti.js
  settings-development.json
Labels: Waiting For Review

#879 Revert "Revert "Release 1.11""
  .meteor/packages
  .meteor/versions
  client/css/_home.scss
  client/head.html
  client/templates/home/home_logged_out.html
  client/templates/home/home_logged_out.js
  client/templates/main.js
  client/templates/study_groups/all_study_groups.html
  client/templates/study_groups/all_study_groups.js
  docker-compose.test.yml
  hooks/post_test
  i18n/en.i18n.json
  imports/data/contributors.json
  package-lock.json
  readme.md
  server/hangouts/publications.js
  server/home/methods.js
  server/monti.js
  settings-development.json
Labels: Waiting For Review

#862 Issue 852: created a global silent hangout page
  .meteor/versions
  client/css/_base.scss
  client/css/_buttons.scss
  client/css/_coworking.scss
  client/css/_fonts.scss
  client/css/_navbar.scss
  client/css/_status_input.scss
  client/css/_status_list.scss
  client/css/style.scss
  client/templates/hangout/hangout-frame.html
  client/templates/hangout/hangout-frame.js
  client/templates/hangout/hangout-learned.html
  client/templates/hangout/hangout-learned.js
  client/templates/nav/header.html
  client/templates/other/coworking.html
  client/templates/other/coworking.js
  client/templates/status/status-list.html
  client/templates/status/status-list.js
  i18n/en.i18n.json
  lib/routes.js
  public/images/jitsi-screenshot-2018.jpg
  server/app_stats/methods.js
  server/learnings/methods.js
Labels: in progress

#877 Format labels and buttons in profile Hangouts Completed
  client/css/_buttons.scss
  client/css/_profile.scss
Labels: Waiting For Review

#882 Update global silent hangout page design
  .meteor/versions
  client/css/_colors.scss
  client/css/_coworking.scss
  client/css/_fonts.scss
  client/css/_navbar.scss
  client/templates/other/coworking.html
  client/templates/other/coworking.js
  i18n/en.i18n.json
Labels: Waiting For Review

#883 Issue 881: PR test
  client/css/_coworking.scss
  client/css/_fonts.scss
  client/templates/other/coworking.html
Labels: Waiting For Review

#884 Issue 881: add coworking image to /coworking page
  client/css/_coworking.scss
  client/templates/other/coworking.html
  public/images/coworking1.jpeg
Labels: Waiting For Review

#886 Issue 871
  server/hangouts/methods.js
  server/slack/methods.js
Labels: In Review

#888 This PR supports unsubscribe links for the following email notifications
  .meteor/packages
  .meteor/versions
  client/templates/settings/unsubscribe_from_mailing_list.html
  client/templates/settings/unsubscribe_from_mailing_list.js
  imports/api/unsubscribe_links/methods.js
  imports/api/unsubscribe_links/server/publications.js
  imports/api/unsubscribe_links/unsubscribe_links.js
  imports/libs/server/cron/helpers.js
  imports/libs/server/cron/initial_email_notifications.js
  imports/startup/server/index.js
  imports/startup/server/register-api.js
  lib/routes.js
  package-lock.json
  package.json
  private/templates/email/new_discussion.html
  private/templates/email/new_discussion_response.html
  private/templates/email/new_hangout.html
  private/templates/email/new_member.html
  server/main.js
Labels: Waiting For Review

#889 PR test: update homepage text
  .meteor/packages
  .meteor/versions
  client/templates/home/home_logged_out.html
  package-lock.json
Labels: Waiting For Review

#893 Issue 892: CSS on mobile fixes
  client/css/_coworking.scss
  client/templates/hangout/hangout-frame.js
Labels: Waiting For Review

#894 Release 1.12
  .meteor/packages
  .meteor/versions
  client/css/_base.scss
  client/css/_buttons.scss
  client/css/_colors.scss
  client/css/_coworking.scss
  client/css/_navbar.scss
  client/css/_profile.scss
  client/css/_status_input.scss
  client/css/_status_list.scss
  client/css/style.scss
  client/templates/hangout/hangout-frame.html
  client/templates/hangout/hangout-frame.js
  client/templates/hangout/hangout-learned.html
  client/templates/hangout/hangout-learned.js
  client/templates/home/home_logged_out.html
  client/templates/nav/header.html
  client/templates/other/coworking.html
  client/templates/other/coworking.js
  client/templates/other/privacy-agreement.html
  client/templates/other/privacy-agreement.js
  client/templates/other/privacy.html
  client/templates/other/terms-of-service.html
  client/templates/profile/profile.html
  client/templates/profile/profile.js
  client/templates/settings/unsubscribe_from_mailing_list.html
  client/templates/settings/unsubscribe_from_mailing_list.js
  client/templates/settings/user_account_settings.html
  client/templates/status/status-list.html
  client/templates/status/status-list.js
  i18n/en.i18n.json
  imports/api/unsubscribe_links/methods.js
  imports/api/unsubscribe_links/server/publications.js
  imports/api/unsubscribe_links/unsubscribe_links.js
  imports/libs/server/cron/helpers.js
  imports/libs/server/cron/initial_email_notifications.js
  imports/startup/server/index.js
  imports/startup/server/register-api.js
  lib/routes.js
  package-lock.json
  package.json
  private/templates/email/new_discussion.html
  private/templates/email/new_discussion_response.html
  private/templates/email/new_hangout.html
  private/templates/email/new_member.html
  public/images/coworking1.jpeg
  public/images/jitsi-screenshot-2018.jpg
  server/app_stats/methods.js
  server/hangouts/methods.js
  server/learnings/methods.js
  server/main.js
  server/slack/methods.js
  server/users/methods.js
  server/users/publications.js
Labels: Waiting For Review

#900 fix (jitsi frame): missing username
  .meteor/versions
  client/templates/hangout/hangout-frame.js
Labels: Waiting For Review

#899 perf(learnings): display total number of learnings
  .meteor/packages
  client/templates/status/status-list.js
  server/learnings/methods.js
Labels: Waiting For Review

#901 Release 1.12 Hotfixes
  .meteor/packages
  .meteor/versions
  client/templates/hangout/hangout-frame.js
  client/templates/status/status-list.js
  imports/data/contributors.json
  server/learnings/methods.js
Labels: Waiting For Review

#904 Solves issue 903: make sure video is always muted by default, even fo…
  .meteor/versions
  client/templates/hangout/hangout-frame.html
  client/templates/hangout/hangout-frame.js
Labels: Waiting For Review
