Repository codebuddies/codebuddies, pull requests merged in 2018-10, with the labels that each got.

#993 Added hangout-learned to profile
  client/templates/profile/profile.html
Labels: Waiting For Review

#997 Add twitter handle to learnings
  server/twitter/methods.js
Labels: Waiting For Review

#999 Updates the hangout card
  client/css/_hangout_board.scss
  client/css/_hangout_card.scss
  client/templates/hangout/hangout_card.html
Labels: Waiting For Review

#1005 _home.scss: Replace hardcoded val with variable
  client/css/_home.scss
Labels: Waiting For Review

#995 Issue 948 default email settings
  client/templates/settings/unsubscribe_from_mailing_list.html
  client/templates/settings/unsubscribe_from_mailing_list.js
  imports/api/unsubscribe_links/methods.js
  server/main.js
  server/users/methods.js
  settings-development.json
Labels: in progress

#1004 Call slack invite api to invite new user to join CodeBuddies workspace
  server/main.js
  server/slack/slack-api.js
Labels: in progress

#1002 Add a button to load more Study Groups
  client/css/_buttons.scss
  client/templates/study_groups/all_study_groups.html
  client/templates/study_groups/all_study_groups.js
  server/study_groups/publications.js
Labels: in progress

#1006 Update deep-extend to 0.5.1
  package-lock.json
Labels: in progress

#1007 Issue#998 hangout card design improvement
  client/css/_fonts.scss
  client/css/_hangout_card.scss
  client/templates/hangout/hangout_action_bar.html
  client/templates/hangout/hangout_card.html
  readme.md
Labels: in progress

#1011 Issue 987: black text on red button
  client/css/_buttons.scss
  client/templates/hangout/hangout_action_buttons.html
Labels: Waiting For Review

#1012 Add contributor username
  .all-contributorsrc
  imports/data/contributors.json
  readme.md
Labels: in progress

#1016 Add contributor: mahamshahid18
  .all-contributorsrc
  imports/data/contributors.json
  readme.md
Labels: Waiting For Review

#1017 Remove the loading screen when loading more on Hangouts Page
  client/templates/hangout/hangout_cards.html
Labels: Waiting For Review

#1015 First version of automatic sending of welcome message to new users.
  .gitignore
  imports/libs/server/user/welcome_email.js
  package-lock.json
  private/templates/email/welcome_message.html
  server/main.js
Labels: Waiting For Review

#1031 Change slack updates channel for dev mode
  settings-development.json
Labels: Waiting For Review

#1030 fixing css bug #1022
  client/css/_sections.scss
Labels: Waiting For Review

#1037 Update readme.md
  readme.md
Labels: Waiting For Review

#973 fix(design): Hide wrong participant msg till its fixed
  client/templates/hangout/hangout-frame.js
Labels: Waiting For Review

#1038 Remove unnecessary alert from clone hangout action
  client/templates/hangout/hangout-clone.js
Labels: in progress

#1025 Updated SweetAlert2 with meteor compatible sweetAlert2
  .meteor/packages
  .meteor/versions
  client/templates/status/learning-item.js
  package-lock.json
  package.json
Labels: Waiting For Review

#1035 Updated SweetAlert2 with meteor compatible sweetAlert2
  client/templates/admin/report/report_discussion_modal.js
  client/templates/admin/report/report_hangout_modal.js
  client/templates/comments/comment_box.js
  client/templates/discussion/discussion_card.js
  client/templates/discussion/discussion_item.js
  client/templates/discussion/discussion_response_card.js
  client/templates/hangout/hangout-clone.js
  client/templates/hangout/hangout-edit.js
  client/templates/hangout/hangout-item.js
  client/templates/hangout/hangout-learned.js
  client/templates/hangout/hangout-modal.js
  client/templates/hangout/hangout.js
  client/templates/hangout/hangout_action_bar.js
  client/templates/hangout/hangout_action_buttons.js
  client/templates/hangout/hangout_card.js
  client/templates/members/member-status.js
  client/templates/settings/delete_my_account_modal.js
  client/templates/status/learning-edit.js
  client/templates/status/learning-item.js
  client/templates/status/update-status.js
  client/templates/study_groups/study_group_discussion.js
  client/templates/study_groups/study_group_settings.js
  settings-development.json
Labels: in progress

#1040 Adding color style to unlike button
  client/css/_buttons.scss
  client/css/_colors.scss
Labels: Waiting For Review

#1029 Fix issue# 1023 Update the "welcome" text on the codebuddies.org/welcome page and welcome email
  client/templates/other/welcome.html
  private/templates/email/welcome_message.html
Labels: in progress

#1043 Issue 1042
  .meteor/packages
  .meteor/versions
  client/layouts/layout.js
  client/templates/status/learning-item.js
  client/templates/study_groups/study_group_settings.js
  package-lock.json
  package.json
Labels: in progress

#1039 Added redirect to welcome page after update to basic information
  imports/ui/pages/users/basic_user_information.js
Labels: Waiting For Review

#1010 Issue: 964 - Star (or highlight) active groups on the /studygroups page
  client/templates/main.js
  client/templates/study_groups/all_study_groups.html
  client/templates/study_groups/all_study_groups.js
  server/discussions/methods.js
  server/hangouts/helpers.js
  server/study_groups/methods.js
  server/study_groups/publications.js
Labels: ready

#1050 Scroll to top of window when landing on /welcome route
  lib/routes.js
Labels: Waiting For Review

#1018 CSS adjustments for hangout card (#1009)
  client/css/_hangout_card.scss
  client/templates/hangout/hangout_card.html
Labels: Waiting For Review

#1054 Resolves issue 1053. Removes extra text from hangout card.
  client/templates/hangout/hangout_card.html
Labels: in progress

#1055 Updated CB homepage copy
  client/templates/home/home_logged_out.html
Labels: Waiting For Review

#1058 Fixes issue 1057: support Github login/signup on sweetalert.
  client/css/_base.scss
  client/css/_colors.scss
  client/layouts/layout.js
  i18n/en.i18n.json
  public/images/github-signin-example.jpg
Labels: in progress

#1048 Update print width from default for configs
  package.json
Labels: Waiting For Review

#1063 Add screenshot for introduce yourself and hangouts on welcome page - #1059
  client/templates/other/welcome.html
  public/images/slack-introduce-yourself.jpg
Labels: Waiting For Review

#1066 Anchor link added issue #1044
  client/css/_slack.scss
  client/templates/other/slack.html
Labels: Waiting For Review

#1060 Fixes issue #1047: add seeder for "discussions" collection.
  server/seeder/database_seed_remover.js
  server/seeder/database_seeder.js
  server/seeder/discussions_collection_seeder.js
Labels: Waiting For Review

#1067 Fix slack hangout reminder alert issue
  private/email-hangout-reminder-two.html
Labels: Waiting For Review

#1008 Renamed Intro to Bio on Sign up and enabled user to edit Skills to Help and Skills to Improve.
  client/templates/profile/profile-edit/profile-edit.html
  client/templates/profile/profile-edit/profile-edit.js
  client/templates/profile/profile.html
  imports/ui/pages/users/basic_user_information.html
  imports/ui/pages/users/basic_user_information.js
  server/users/methods.js
Labels: in progress
