Repository codebuddies/codebuddies, pull requests merged in 2018-09, with the labels that each got.

#943 Allow user to create hangouts from slack
  .meteor/versions
  package.json
  server/hangouts/helpers.js
  server/hangouts/methods.js
  server/routes.js
  server/slack/message-parser.js
  server/slack/slack-api.js
  server/slack/webhooks.js
  settings-development.json
Labels: in progress

#952 Feature/hangout from slack
  package.json
  server/hangouts/helpers.js
  server/hangouts/methods.js
  server/routes.js
  server/slack/message-parser.js
  server/slack/slack-api.js
  server/slack/webhooks.js
  settings-development.json
Labels: in progress

#953 Add more contributors to the about page
  .all-contributorsrc
  imports/data/contributors.json
  readme.md
Labels: in progress

#954 Hotfix to add contributors
  .all-contributorsrc
  imports/data/contributors.json
  readme.md
  server/hangouts/methods.js
Labels: in progress

#955 Add more contributors
  .all-contributorsrc
Labels: in progress

#956 Add Bill
  .all-contributorsrc
  readme.md
Labels: in progress

#957 Fix Issue-932
  client/css/_base.scss
  client/templates/other/slack.html
Labels: Waiting For Review, in progress

#960 Adding console.log to debug JARVIS
  server/slack/message-parser.js
Labels: in progress

#961 Fixed: Jarvis constantly returns "Date unrecognized. Please try Again." even for valid date!
  server/slack/message-parser.js
Labels: in progress

#965 added HTML in place of Slack widget
  client/templates/home/home_logged_out.html
  package-lock.json
Labels: Waiting For Review

#966 New release: 1.2.1
  .all-contributorsrc
  client/css/_base.scss
  client/templates/home/home_logged_out.html
  client/templates/other/slack.html
  package-lock.json
  readme.md
  server/slack/message-parser.js
Labels: in progress
