Repository codebuddies/codebuddies, pull requests merged in 2019-03, with the labels that each got.

#1130 Issue 1122
  client/templates/discussion/add_discussion_modal.html
  client/templates/discussion/discussion_new_response.html
  package-lock.json
Labels: in progress

#1132 remove column names and add created by to discussion item
  client/templates/discussion/all_discussions.html
  client/templates/discussion/discussion_item.html
Labels: Waiting For Review

#1133 Remove semicolon in timestamp of a comment
  client/templates/discussion/discussion_card.html
  client/templates/discussion/discussion_item.html
  client/templates/discussion/discussion_response_card.html
  client/templates/study_groups/study_group_discussion.html
Labels: Closed

#1134 Resolved issue #1128
  imports/data/discussion_tags.js
Labels: Waiting For Review
